feat: add file creation command
gartmeier/kudu pull request #14
Opened 2023-03-08 08:02 UTC by AykutBurak

### Description
We want to be able to create new files with each realease rather than updating the exisiting ones.
For that I've added the command `create` in this PR.

2023-03-08 08:44 UTC, gartmeier requested changes

2023-03-08 08:44 UTC, gartmeier commented on kudu/commands/create.py
> +@click.option('--appid', '-a', type=int, required=True, help="appId")
Can you rename the option's parameter to `--instance, -i`or make it an argument since it is required

2023-03-08 08:44 UTC, gartmeier commented on kudu/commands/create.py
> +@click.option('--body', '-b', type=str, required=True, help="Body of the file")
Can you use the file type? https://click.palletsprojects.com/en/8.1.x/api/#click.File

2023-03-08 08:44 UTC, gartmeier commented on kudu/commands/create.py
> +    token = ctx.obj['token']
this line only adds noise and no actual value or improves readability

2023-03-08 08:44 UTC, gartmeier commented on kudu/commands/init.py
> +def create_file(token, app_id, file_body, download_url = None):
Can we move both create and update file functions to `kudu.api`?

2023-03-08 08:44 UTC, gartmeier commented on kudu/commands/create.py
> +    upload_file(token, pitcher_file)
Why is this function 1st creating a file and uploading it in the second step, not both with one request?

2023-03-08 15:17 UTC, AykutBurak commented on kudu/commands/create.py
> +@click.option('--body', '-b', type=str, required=True, help="Body of the file")
This is the `body` text of the file to be created on the admin. This command uses a similar approach with `push`; it uploads the contents of the file it's run

2023-03-08 15:19 UTC, AykutBurak commented on kudu/commands/create.py
> +    upload_file(token, pitcher_file)
rest api wasn't accepting direct file uploads - now it makes only one request to the api

2023-03-20 11:08 UTC, cevrim approved these changes
LGTM, but would be nice to fix the failing action

2023-03-21 11:52 UTC, gartmeier approved these changes

2023-03-21 13:11 UTC, merged